backend:
  name: github
  repo: spetsura/Spetsura_Terminal
  branch: master
  base_url: https://spetsura.com
  auth_endpoint: /api/cms/auth
  
media_folder: "content/images"
public_folder: "/content/images"

publish_mode: editorial_workflow

collections:
  - name: "static-pages"
    label: "Static Pages"
    files:
      - file: "content/notes.md"
        label: "Notes"
        name: "notes"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "content/resume.md"
        label: "Resume"
        name: "resume"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
