name: CI/CD Approval & Sudo Test

on:
  workflow_dispatch: {}   

jobs:
  approve-and-test:
    runs-on: [selfhosted, prod]   
    environment:
      name: production            
    steps:
      - name: Who am I
        run: |
          echo "Runner: $RUNNER_NAME"
          whoami
          id

      - name: Create test release dir (no sudo)
        run: |
          set -euo pipefail
          APP_DIR=/var/www/myapp
          TS=$(date +%Y%m%d%H%M%S)
          REL=$APP_DIR/releases/CI_TEST_$TS
          mkdir -p "$REL"
          echo "hello from CI at $TS" > "$REL/README.txt"
          ls -la "$REL"
          echo "Test dir created at: $REL"

      - name: Test limited sudo permissions (nginx check & reload)
        run: |
          sudo nginx -t
          sudo systemctl reload nginx || true
          echo "nginx test & reload done"

      - name: Success marker
        run: echo "Everything looks good bruh! ✅"
